apiVersion: v1
kind: Service
metadata:
  name: index-client-service
  namespace: default
  labels:
    app: index-client
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: index-client
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None